spring.application.name=back

spring.datasource.url=jdbc:mysql://localhost:3306/datawarehouse
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=bandsmileclinic@gmail.com
spring.mail.password=yulqbtxobnewgixr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.from=BandSmile <bandsmileclinic@gmail.com>

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail.smtp=DEBUG


